"""
Enformer Signal Evaluation: Correlation & Metadata Analysis

This script produces the evaluation TSV containing Pearson and Spearman 
correlations between "true" experimental signal values and predicted values 
generated by the Enformer model. It also produces the foldchange evaluations.
Note that the foldchange evaluations have half the number of peaks because
reverse complements were not passed into enformer.

Methodology:
For Enformer evaluations, we take the middle 4 bins (indices 446:450) to cover 
the 512 bp of the summit center (128 bp per bin). Empirical testing has shown 
that this 4-bin window produces the best correlations compared to other 
bin counts. 

Slicing Reference:
- 512 bp (Current): preds_raw[:, 446:450]
- 1024 bp (Alternative): preds_raw[:, 444:452]

Workflow:
1. Iterates through subdirectories in ENFORMER_OUTPUTS.
2. For all directories: Calculates global metadata (mean, std, count) per species.
3. For positive sets (excluding 'log_test1' and 'neg'): Loads ground-truth 
   signal from corresponding BED files and calculates Pearson/Spearman 
   coefficients.
4. For test2: Loads mouse positive true values and predictions
   and compares with the given species test2.
5. Outputs:
   - correlations.tsv: Statistical evaluation of model performance.
   - all_metadata.tsv: Global signal statistics and baseline values.
   - foldchange_results.tsv: Foldchange evaluation.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import pearsonr, spearmanr
from pathlib import Path
from sklearn.metrics import mean_squared_error
import os

ENFORMER_INPUTS = Path("/home/azstephe/liverRegression/regression_liver/data/enformer_inputs/")
ENFORMER_OUTPUTS = Path("/home/azstephe/liverRegression/regression_liver/data/enformer_outputs/")

results_list = []
meta_results = []
dir_list = ['log_test2', 'log_test1']

for subdir_name in dir_list:
# for subdir_name in os.listdir(ENFORMER_OUT):
    subdir_path = ENFORMER_OUTPUTS / subdir_name
    if not subdir_path.is_dir(): 
        continue

    # dict to collect averages for global metadata (per species)
    meta_collector = {}

    # change the keyword for your saved npy file
    for pred_path in subdir_path.glob("*_205_preds.npy"):
        species = pred_path.name.split('_')[0]

        # load enformer predictions and average the 4 middle bins (446:450)
        preds_raw = np.load(pred_path) # shape (N, 896)
        preds_avg = np.mean(preds_raw[:, 446:450], axis=1).flatten()

        # collect meta for all subdirs
        if species not in meta_collector:
            meta_collector[species] = []
        meta_collector[species].extend(preds_avg)

        # calculate correlations for positives only
        if subdir_name not in ['log_test1', 'neg']:
            bed_path = ENFORMER_INPUTS / subdir_name / f'{species}_liver_TEST_500bp.bed'
            
            if bed_path.exists():
                # load true values
                true_values = pd.read_csv(bed_path, header=None, sep=r'\s+').iloc[:, 4].values

                # check we are comparing the correct files - will error out
                if len(preds_avg) != len(true_values):
                    print(f"Warning: Size mismatch! Preds: {len(preds_avg)}, True: {len(true_values)}")

                r, p = pearsonr(true_values, preds_avg)
                s, sp = spearmanr(true_values, preds_avg)
                results_list.append({
                    'subdir': subdir_name, 'species': species,
                    'pearson_r': r, 'pearson_p': p, 
                    'spearman_rho': s, 'spearman_p': sp, 
                    'n': len(preds_avg)
                })

    # finalize metadata
    for species, all_preds in meta_collector.items():
        if all_preds:
            meta_results.append({
                'subdir': subdir_name,
                'species': species,
                'global_avg': np.mean(all_preds),
                'std_dev': np.std(all_preds),
                'count': len(all_preds)
            })

# save outputs
META_DIR = Path("/home/azstephe/liverRegression/regression_liver/data/enformer_meta/")
META_DIR.mkdir(parents=True, exist_ok=True)

pd.DataFrame(results_list).to_csv(META_DIR / "correlations.tsv", sep='\t', index=False)
pd.DataFrame(meta_results).to_csv(META_DIR / "all_metadata.tsv", sep='\t', index=False)

###
# FOLDCHANGE SECTION
###

ONE_TO_ONE_DIR = Path("/home/azstephe/liverRegression/regression_liver/data/test_splits/oneToOnePeaks/")

species_list = ['macaque', 'rat', 'cow', 'pig']

def format_result_value(metric, value):
    """Format values based on the metric type provided."""
    if "Count" in metric:
        return int(value)
    elif "P-Val" in metric:
        return f"{value:.2E}"
    elif "%" in metric or metric in ["Pearson", "Spearman", "MSE"]:
        return round(float(value), 3)
    return value
    
def get_signal_dict(bed_path, pred_path):
    """Maps Peak ID to the averaged Enformer prediction and True value."""
    bed = pd.read_csv(bed_path, sep=r'\s+', header=None)
    true_map = dict(zip(bed[3], bed[4]))
    
    preds_raw = np.load(pred_path)
    # average the middle 4 bins (512bp)
    preds_avg = np.mean(preds_raw[:, 446:450], axis=1).flatten()
    
    pred_map = dict(zip(bed[3], preds_avg))
    return true_map, pred_map

rows = []

for species in species_list:
    bridge_path = ONE_TO_ONE_DIR / f"{species}_mouse.bed"
    if not bridge_path.exists(): continue
    bridge = pd.read_csv(bridge_path, header=None, sep='\t')
    
    m_true, m_pred = get_signal_dict(
        ENFORMER_INPUTS / "log_pos" / "mouse_liver_TEST_500bp.bed",
        ENFORMER_OUTPUTS / "log_pos" / "mouse_liver_TEST_enformer_205_preds.npy"
    )
    
    s_true, s_pred = get_signal_dict(
        ENFORMER_INPUTS / "log_test2" / f"{species}_liver_TEST_500bp.bed",
        ENFORMER_OUTPUTS / "log_test2" / f"{species}_liver_TEST_enformer_205_preds.npy"
    )

    # align orthologs
    data = []
    for _, row in bridge.iterrows():
        s_id, m_id = row[4], row[14]
        if m_id in m_true and s_id in s_true:
            data.append({
                'm_true': m_true[m_id], 'm_pred': m_pred[m_id],
                's_true': s_true[s_id], 's_pred': s_pred[s_id]
            })
    
    df = pd.DataFrame(data)
    if df.empty: continue

    # calculate fold changes
    x = df['m_true'] - df['s_true']
    y = df['m_pred'] - df['s_pred']
    
    pearson, pp = scipy.stats.pearsonr(x, y)
    spearman, ps = scipy.stats.spearmanr(x, y)
    mse = mean_squared_error(x, y)
    
    num_ss = (np.sign(x) == np.sign(y)).sum()
    perc_ss = num_ss / len(df)

    metrics = [
        ('Same Sign Count', num_ss),
        ('Total Count', len(df)),
        ('Same Sign %', perc_ss),
        ('Pearson', pearson),
        ('Pearson P-Val', pp),
        ('Spearman', spearman),
        ('Spearman P-Val', ps),
        ('MSE', mse)
    ]

    for metric_name, value in metrics:
        formatted_val = format_result_value(metric_name, value)
        rows.append({
            'Species': species,
            'Group': 'Test2',
            'Metric': metric_name,
            'Enformer': formatted_val
        })

results_df = pd.DataFrame(rows)

# save to TSV
output_path = META_DIR / "foldchange_results.tsv"
results_df.to_csv(output_path, sep='\t', index=False)
